### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by gumil** [Survicate/survicate-android-sdk#10]
Hey what are the suggested proguard rules that Survicate should have?

We keep getting crashes because of obfuscated classes.

We had this proguard rules:
```
-keep @com.squareup.moshi.JsonQualifier class *
-keep public class com.survicate.surveys.entities.** { *; }
```

It didn't crash but it keeps getting caught NullPointerExceptions in logcat.

**Comment by j-brzozowski** [comment]
Could you try to enable logging?
Pls define second parameter in `init()` method:
```
Survicate.init(this, true);
```

**Comment by gumil** [comment]
Yes I saw the NPEs because I enabled the logging

**Comment by j-brzozowski** [comment]
Can you paste full exception message from logcat?
What is your workspace key?

**Comment by gumil** [comment]
The full exception is obfuscated and is and not informative. But it relates to network requests I think.

**Comment by gumil** [comment]
To also fix any possible errors we obfuscated the whole survicate package.

**Comment by j-brzozowski** [comment]
What gradle version do you have?

Have you enabled R8 in your `gradle.properties` file?
`android.enableR8=true`

**Comment by j-brzozowski** [comment]
If you still have any issues, do not hesitate contact us using Intercom or email.
