### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by kinjal1928** [Survicate/survicate-android-sdk#2]
error: failed linking references.

I having trouble while adding this SDK to my Android project. I also tried creating a new project and it run successfully and now i'm trying to add library in my working project but it gives error while syncing but having  issue.
Gradle project sync fails every time.

below is my added dependencies:
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.google.firebase:firebase-crash:11.8.0'
    compile 'com.android.support:support-v4:26.+'
    compile 'com.android.support:design:26.0.2'
    implementation 'jp.wasabeef:glide-transformations:3.1.0'
    compile 'com.github.bumptech.glide:annotations:4.6.1'
    compile 'com.google.android.gms:play-services-places:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'
    implementation 'com.google.android.gms:play-services-maps:11.8.0'
    implementation 'com.google.android.gms:play-services-location:11.8.0'
    testCompile 'junit:junit:4.12'
    testCompile 'org.json:json:20140107'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'com.intuit.sdp:sdp-android:1.0.4'
    compile 'cn.aigestudio.wheelpicker:WheelPicker:1.1.2'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'com.nhaarman.supertooltips:library:3.0.0'
    compile 'it.sephiroth.android.library.targettooltip:target-tooltip-library:1.3.15'
    compile 'com.daasuu:BubbleLayout:1.2.0'
    compile 'com.google.code.gson:gson:2.8.2'
    compile 'com.android.support:recyclerview-v7:26.0.2'
    testCompile 'org.mockito:mockito-core:2.7.22'
    androidTestCompile 'org.mockito:mockito-android:2.7.22'
    compile 'com.github.santalu:aspect-ratio-imageview:1.0.3'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    compile 'com.github.oxoooo:pull-back-layout:1.0.1'
    compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.bugfender.sdk:android:1.1'
    compile 'org.jsoup:jsoup:1.7.3'
    compile 'com.google.android.gms:play-services-analytics:11.8.0'
    **compile 'com.survicate:survicate-sdk:1.+'**
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'com.stripe:stripe-android:6.1.2'
    implementation project(':library')
    testCompile 'org.robolectric:robolectric:3.8'
    implementation 'com.facebook.android:facebook-android-sdk:[4,5)'
    compile('com.crashlytics.sdk.android:crashlytics:2.9.3@aar') {
        transitive = true
    }
    implementation files('libs/google_conversion_tracking_sdk.jar')

}

**Comment by akshit-zaveri** [comment]
+1

**Comment by j-brzozowski** [comment]
@kinjal1928 do you still have any issues?

**Comment by akshit-zaveri** [comment]
@j-brzozowski  Yes the issue was fixed.
