### ISSUE TITLE
Issue with your new library version 1.0.7 ( Fail to resolve androidx libraries )

### ISSUE THREAD

**Issue by jash0612** [Survicate/survicate-android-sdk#3]
Getting below errors while project build:

ERROR: Failed to resolve: androidx.appcompat:appcompat-support:1.0.2
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: androidx.cardview:cardview-support:1.0.0
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: androidx.recyclerview:recyclerview-support:1.0.0
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: androidx.constraintlayout:constraintlayout-support:1.1.3
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: com.squareup.moshi:moshi-support:1.8.0
Show in Project Structure dialog
Affected Modules: app

ERROR: Failed to resolve: androidx.transition:transition-support:1.0.1
Show in Project Structure dialog
Affected Modules: app

Please fix the issue. Thanks in advance

**Comment by j-brzozowski** [comment]
@jash0612 we just released 1.0.8 version. Does your problem still exists?
