### ISSUE TITLE
Resource not found issue

### ISSUE THREAD

**Issue by sayedhassan** [Survicate/survicate-android-sdk#4]
I am trying to integrate survicate into our existing android project and it won't compile. Here is the compilation error :
` AGPBI: {"kind":"error","text":"No resource found that matches the given name (at \u0027layout_constraintTop_toTopOf\u0027 with value \u0027@id/survicate_scroll_top_gradient_overlay\u0027).","sources":[{"file":"/Users/sayed.hassan/.gradle/caches/transforms-1/files-1.1/survicate-sdk-1.0.12.aar/c87d22346a0013c4d1959f6cbe31268d/res/layout/fragment_survey_point.xml","position":{"startLine":41,"startColumn":50,"startOffset":2090,"endColumn":91,"endOffset":2131}}],"original":"","tool":"AAPT"} `

**Comment by piotr-survicate** [comment]
Hi! 
Please give us some time to work on it, we'll come back to you soon

**Comment by piotr-survicate** [comment]
By the way, which version of SDK do you use?

**Comment by sayedhassan** [comment]
Thanks @piotr-survicate . I am using 1.0.12 as shown in the logs. Also, the documentation doesn't say what is the latest version of the sdk. I browsed through https://repo.survicate.com to find the version

**Comment by piotr-survicate** [comment]
Could you please tell me if you have custom proguard setup and share your build.gradle file with me?

**Comment by piotr-survicate** [comment]
Hi, we have just released 1.0.13 version of our SDK, that should solve this problem.
