### ISSUE TITLE
userid not showing  in dashboard on admin panel

### ISSUE THREAD

**Issue by akshamala99** [Survicate/survicate-android-sdk#5]
Survicate.reset();
                    List<UserTrait> traits = new ArrayList<>();
                    traits.add(new UserTrait.UserId("1169));
                    traits.add(new UserTrait.LastName("rame));
                   traits.add(newUserTrait.FirstName("pawankumar"));
                    traits.add(new UserTrait.Address.State("delhi));
                 
                    Survicate.setUserTraits(traits);
                  
                    Survicate.enterScreen(SCREEN_KEY);

i am initiating the request to Survicate using the above code and its working great on my android device however the user_Id parameter that we are setting is not showing the admin dashboard panel

please look  into this Issue and kindly resolve it A.S.A.P
Thanks...

**Comment by piotr-survicate** [comment]
Hi!
We are aware of this issue and we ought to solve it this week. I will let you know as soon as we resolve it.

**Comment by piotr-survicate** [comment]
Hi! Sorry for the delay, but I do believe we continued the conversation on Intercom :)
Everything should be fixed with the newest SDK version
